[package]
name = "hamming-bow"
version = "0.1.0"
edition = "2018"

[dependencies]
bitarray = { version = "0.5.1", default-features = false }
hamming-dict = { version = "0.1.0", default-features = false, features = ["alloc"] }
